# -*- coding: utf-8 -*-
"""Github submit version 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aoM0kJiWcEx2YSihnqG9pCe2q7XFifJY
"""

pip install rapidfuzz

#NOTES: THIS CODE IS SPLIT INTO 5 PARTS AND CONSOLIDATED ONTO 1 FILE AND TAKES ABOUT 5 MINUTES TO RUN




"""
# PART 1: Kenpom and Batorvik Webscraping and merging


"""



#pip install rapidfuzz #uncomment if you need to install

# @title
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO
from rapidfuzz import process, fuzz
import time


headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
}

# Cutoff = Selection Sunday for each year (no tournament games included)
SELECTION_SUNDAY = {
    2026: '20260315',
    2025: '20250316',
    2024: '20240317',
    2023: '20230312',
    2022: '20220313',
    2021: '20210314',
    # 2020 skipped — no tournament
    2019: '20190317',
    2018: '20180311',
    2017: '20170312',
    2016: '20160313',
    2015: '20150315',
    2014: '20140316',
    2013: '20130317',
    2012: '20120311',
    2011: '20110313',
    2010: '20100314',
}


"""Scrape from Kenpom"""

# @title
# --------------------------------------------------
#  KenPom
# --------------------------------------------------

def extract_td_by_index(row, index):
    tds = row.find_all('td')
    if index >= len(tds):
        return None
    value = tds[index].text.strip()
    return value if value else None

def extract_team_and_seed(team_str):
    if team_str is None:
        return None, None
    parts = team_str.strip().rsplit(' ', 1)
    if len(parts) == 2 and parts[1].isdigit():
        return parts[0], parts[1]
    return team_str, None

def extract_kenpom(year, cutoff_date):
    COLUMN_MAP = {
        'rank': 0, 'team': 1, 'conf': 2, 'w_l': 3, 'net_rtg': 4,
        'ORtg': 5, 'ORtg_rank': 6, 'DRtg': 7, 'DRtg_rank': 8,
        'Adjusted_Tempo': 9, 'tempo_rank': 10, 'luck': 11, 'luck_rank': 12,
        'NetRTg_sos': 13, 'ORtg_sos': 14, 'Drtg_sos': 15, 'ncsos_rank': 16,
    }
    # snapshot on Selection Sunday — stats reflect reg season only
    url = f'https://kenpom.com/index.php?y={year}&d={cutoff_date}'
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')

    records = []
    for row in soup.find_all('tr'):
        tds = row.find_all('td')
        if len(tds) < 5:
            continue
        record = {col: extract_td_by_index(row, idx) for col, idx in COLUMN_MAP.items()}
        if record['rank'] and record['rank'].isdigit():
            record['team'], record['seed'] = extract_team_and_seed(record.get('team'))
            records.append(record)

    df = pd.DataFrame(records)
    df['year'] = year
    return df

# --------------------------------------------------
#  Barttorvik
# --------------------------------------------------


def extract_barttorvik(year, cutoff_date):
    # end=<Selection Sunday> — excludes tournament games
    url = (
        f'https://barttorvik.com/teamslicejson.php'
        f'?year={year}&json=1&type=All'
        f'&begin={year-1}1101&end={cutoff_date}'
    )
    r = requests.get(url, headers=headers)
    data = r.json()

    records = []
    for row in data:
        records.append({
            'team':      row[0],
            'adjoe':     row[1],
            'adjde':     row[2],
            'barthag':   row[3],
            'record':    row[4],
            'wins':      row[5],
            'losses':    row[6],
            'efg':       row[7],
            'efgd':      row[8],
            'ftr':       row[9],
            'ftrd':      row[10],
            'tor':       row[11],
            'tord':      row[12],
            'orb':       row[13],
            'drb':       row[14],
            '2p':        row[16],
            '2pd':       row[17],
            '3p':        row[18],
            '3pd':       row[19],
            '3pr':       row[24],
            '3prd':      row[25],
            'adj_tempo': row[26],
            'wab':       row[34],
            'year':      year,
        })
    return pd.DataFrame(records)


"""Fuzzy merge"""

# @title
# --------------------------------------------------
#  Fuzzy merge
# --------------------------------------------------

def merge_year(year, cutoff_date):
    print(f"  KenPom snapshot @ {cutoff_date} ...")
    kenpom = extract_kenpom(year, cutoff_date)
    time.sleep(3)

    print(f"  Barttorvik end @ {cutoff_date} ...")
    bart = extract_barttorvik(year, cutoff_date)
    time.sleep(3)

    bart_teams = bart['team'].tolist()
    kenpom['team_matched'] = kenpom['team'].apply(
        lambda name: process.extractOne(name, bart_teams, scorer=fuzz.token_sort_ratio)[0]
        if name is not None else None
    )
    bart = bart.rename(columns={'team': 'team_matched'})
    merged = kenpom.merge(bart, on='team_matched', how='left', suffixes=('_kenpom', '_bart'))
    merged = merged.drop(columns=['team_matched'])
    return merged



"""Main Code, create a csv with regular season stats"""

# @title
# --------------------------------------------------
#  Main
# --------------------------------------------------

all_years = []
for year, cutoff in sorted(SELECTION_SUNDAY.items()):
    print(f"\n=== {year} (cutoff: {cutoff}) ===")
    try:
        df = merge_year(year, cutoff)
        all_years.append(df)
        print(f"  OK — {len(df)} teams")
    except Exception as e:
        print(f"  ERROR: {e}")

final = pd.concat(all_years, ignore_index=True)
final.to_csv('RegSeasonStats.csv', index=False)
print(f"\nDone! {len(final)} rows → RegSeasonStats.csv")

#rename the year_bart column to Season
pd.read_csv("RegSeasonStats.csv").rename(columns={'year_bart': 'Season'}).to_csv("RegSeasonStats.csv", index=False)

print(pd.read_csv("RegSeasonStats.csv").columns.tolist())

kenpom_cols = ['w_l', 'net_rtg', 'ORtg', 'ORtg_rank', 'DRtg', 'DRtg_rank', 'Adjusted_Tempo', 'tempo_rank', 'luck', 'luck_rank', 'NetRTg_sos', 'ORtg_sos', 'Drtg_sos', 'ncsos_rank']
pd.read_csv("RegSeasonStats.csv").drop(columns=[c for c in kenpom_cols if c in pd.read_csv("RegSeasonStats.csv").columns]).to_csv("RegSeasonStats.csv", index=False)
print(pd.read_csv("RegSeasonStats.csv").iloc[0])

print("Part 1 complete")



"""# PART 2: Getting Tournament Win/Loss Records
<h2>Imported a teamID legend and win/loss data by team ID and combining so we have Team Names too</h2>
<h3>Source: Kaggle 2026 March Madness Machine Learning Competition</h3>


NOTE: YOU NEED TO DOWNLOAD 2 KAGGLE FILES. THEY ARE ATTACHED IN THE GITHUB LABELLED AS: MMHistoricResults.csv AND MTeams.csv

"""

# @title
import pandas as pd

games = pd.read_csv("MMHistoricResults.csv")
teams = pd.read_csv("MTeams.csv")


"""Games head"""

# @title
games.head()

"""Teams head"""

# @title
teams.head()

"""Updated CSV file"""

# @title

import pandas as pd

games = pd.read_csv("MMHistoricResults.csv")
teams = pd.read_csv("MTeams.csv")

games = games[(games["Season"] >= 2010) & (games["Season"] <= 2026)] #in case other years came into dataset, we only want to look at 2010 and on

#adding name to winning team stats
games = games.merge(
    teams[["TeamID", "TeamName"]], how="left",left_on="WTeamID", right_on="TeamID"
)
games = games.rename(columns={"TeamName": "WTeamName"})
games = games.drop(columns=["TeamID"]) # no longer needed

##adding name to losing team stats
games = games.merge(
    teams[["TeamID", "TeamName"]], how="left", left_on="LTeamID", right_on="TeamID"
)

games = games.rename(columns={"TeamName": "LTeamName"})
games = games.drop(columns=["TeamID"])

#games.head()


games.to_csv("MMHistoricResultsNEW.csv", index=False)
#updated csv file with everything

#compute empirical win rates by seed matchup from your tournament data

"""# PART 3: Combining datasets into one large set</h1>
<h2>Each row is a tournament game with each teams stats</h2>
<h3></h3>


"""


#V2
import pandas as pd
import numpy as np
import re

# Change these filenames if needed
GAMES_PATH = "MMHistoricResultsNEW.csv"
STATS_PATH = "RegSeasonStats.csv"
MEGA_OUT = "MarchMadness_MegaDataset_2010_2025.csv"
MODEL_OUT = "MarchMadness_ModelDataset_2010_2025.csv"

games = pd.read_csv(GAMES_PATH)
stats = pd.read_csv(STATS_PATH)

# Keep only seasons that actually have tournament game results
stats = stats[stats["Season"].isin(games["Season"].unique())].copy()

def strip_seed_from_team(s):
  '''
  removes uneeded symbols and seed numbers from team names. neccesary due to the kenpom data.
  '''
  s = str(s).strip()
  parts = s.split()

  last_part = parts[-1]

  if last_part.replace("*", "").isdigit() and "*" in last_part:
      parts = parts[:-1]

  return " ".join(parts)

def base_norm(s):
  '''
  standardizes the team names so that theyre easier to read across files
  '''
  s = strip_seed_from_team(s).lower().strip()
  s = s.replace("&", "and")
  s = re.sub(r"[\.\'’]", "", s)
  s = s.replace("-", " ")
  s = re.sub(r"\s+", " ", s).strip()
  return s

#Methodically translated naming discrepancies so they are the some
alias = {
    "ark pine bluff": "arkansas pine bluff",
    "st marys ca": "saint marys",
    "ut san antonio": "utsa",
    "wku": "western kentucky",
    "st louis": "saint louis",
    "nc aandt": "north carolina aandt",
    "fgcu": "florida gulf coast",
    "suny albany": "albany",
    "n dakota st": "north dakota st",
    "sf austin": "stephen f austin",
    "mt st marys": "mount st marys",
    "mtsu": "middle tennessee",
    "st josephs pa": "saint josephs",
    "tx southern": "texas southern",
    "f dickinson": "fairleigh dickinson",
    "abilene chr": "abilene christian",
    "tam c christi": "texas aandm corpus chris",
    "fl atlantic": "florida atlantic",
    "grambling": "grambling st",
    "mcneese st": "mcneese",
    "etsu": "east tennessee st",
    "ark little rock": "arkansas little rock",
    "n colorado": "northern colorado",
    "boston univ": "boston university",
    "st peters": "saint peters",
    "ms valley st": "mississippi valley st",
    "s dakota st": "south dakota st",
    "southern univ": "southern",
    "northwestern la": "northwestern st",
    "w michigan": "western michigan",
    "wi milwaukee": "milwaukee",
    "american univ": "american",
    "nc central": "north carolina central",
    "e kentucky": "eastern kentucky",
    "g washington": "george washington",
    "coastal car": "coastal carolina",
    "e washington": "eastern washington",
    "cs bakersfield": "cal st bakersfield",
    "wi green bay": "green bay",
    "n kentucky": "northern kentucky",
    "kent": "kent st",
    "prairie view": "prairie view aandm",
    "cs fullerton": "cal st fullerton",
    "se missouri st": "southeast missouri st",
    "col charleston": "charleston",
    "college of charleston": "charleston",
    "kennesaw": "kennesaw st",
    "st francis pa": "saint francis",
    "ne omaha": "nebraska omaha",
    "louisiana lafayette": "louisiana",
}

def team_key(s):
  '''
  creates a clean name key for each team and if they are in the nicknames above we apply that
  '''
  k = base_norm(s)
  return alias.get(k, k)


#clean team names
stats["team_clean"] = stats["team"].apply(strip_seed_from_team)
stats["team_key"] = stats["team_clean"].apply(team_key)
games["W_team_key"] = games["WTeamName"].apply(team_key)
games["L_team_key"] = games["LTeamName"].apply(team_key)

#Each team has one stat row per season
Wstats = stats.add_prefix("W_")
Lstats = stats.add_prefix("L_")
mega = games.merge(
    Wstats,
    left_on=["Season", "W_team_key"],
    right_on=["W_Season", "W_team_key"],
    how="left"
)
mega = mega.merge(
    Lstats,
    left_on=["Season", "L_team_key"],
    right_on=["L_Season", "L_team_key"],
    how="left"
)

#adding differntial columns - neccesary for proper feature analysis
non_feature = {"Season", "year", "team_key", "team_clean", "team", "conf", "w_l", "record"}
base_cols = [c for c in stats.columns if c not in non_feature]


winner_data = {}
loser_data = {}

for column in base_cols:
    winner_column = "W_" + column

    if winner_column in mega.columns:
        winner_data[column] = pd.to_numeric(mega[winner_column], errors="coerce") #inputs 'Nan' if no data


for column in base_cols: #repeated for losing teams
    loser_column = "L_" + column

    if loser_column in mega.columns:
        loser_data[column] = pd.to_numeric(mega[loser_column], errors="coerce")

#create difference columns subtracting losing value from winning value. very important for machine learning coefficent analysis
for column in base_cols:
    if column in winner_data and column in loser_data:
        if winner_data[column].notna().any() and loser_data[column].notna().any():
            mega[column + "_diff"] = winner_data[column] - loser_data[column]


#renaming
mega["Winner"] = mega["WTeamName"]
mega["Loser"] = mega["LTeamName"]
mega["winner_first"] = 1

#move main stats to the front
front = ["Season", "DayNum", "WTeamID", "WTeamName", "WScore", "LTeamID", "LTeamName", "LScore", "Winner", "Loser", "WLoc", "NumOT"]
front = [c for c in front if c in mega.columns]
mega = mega[front + [c for c in mega.columns if c not in front]]
mega.to_csv(MEGA_OUT, index=False) #output the MEGA dataset - our 1 tournament game w/ stats per row dataset


#creating a model dataset which uses the data and is needed to train models.
#first we rename from winning and losers and to team 1 and 2.
model_games = games.copy()
team1_is_winner = model_games["WTeamID"] < model_games["LTeamID"]
model_games["Team1Name"] = np.where(team1_is_winner, model_games["WTeamName"], model_games["LTeamName"])
model_games["Team2Name"] = np.where(team1_is_winner, model_games["LTeamName"], model_games["WTeamName"])
model_games["Team1ID"] = np.where(team1_is_winner, model_games["WTeamID"], model_games["LTeamID"])
model_games["Team2ID"] = np.where(team1_is_winner, model_games["LTeamID"], model_games["WTeamID"])
model_games["Team1Score"] = np.where(team1_is_winner, model_games["WScore"], model_games["LScore"])
model_games["Team2Score"] = np.where(team1_is_winner, model_games["LScore"], model_games["WScore"])
model_games["Team1_key"] = model_games["Team1Name"].apply(team_key)
model_games["Team2_key"] = model_games["Team2Name"].apply(team_key)
model_games["Team1Win"] = np.where(team1_is_winner, 1, 0)

T1 = stats.add_prefix("T1_")
T2 = stats.add_prefix("T2_")
model = model_games.merge(T1, left_on=["Season", "Team1_key"], right_on=["T1_Season", "T1_team_key"], how="left")
model = model.merge(T2, left_on=["Season", "Team2_key"], right_on=["T2_Season", "T2_team_key"], how="left")

for c in base_cols:
    t1, t2 = "T1_" + c, "T2_" + c
    if t1 in model.columns and t2 in model.columns: #only use stats shared by both teams
        n1 = pd.to_numeric(model[t1], errors="coerce")
        n2 = pd.to_numeric(model[t2], errors="coerce")
        if n1.notna().any() and n2.notna().any():
            model[c + "_diff"] = n1 - n2

front2 = ["Season", "DayNum", "Team1ID", "Team1Name", "Team1Score", "Team2ID", "Team2Name", "Team2Score", "Team1Win", "WTeamName", "LTeamName", "WScore", "LScore"]
model = model[front2 + [c for c in model.columns if c not in front2]]

#model csv dataset is ready!
model.to_csv(MODEL_OUT, index=False)

print("Mega dataset saved:", MEGA_OUT, mega.shape) #ensuring the dataset is truly MEGA
print("Model dataset saved:", MODEL_OUT, model.shape)


print("Parts 2 and 3 complete")

"""# PART 4: Developing Models
<h2>Using the webscraped dataset from above</h2>
<h3>1) seed only 2) logistic regression 3) random forest 4) neural network</h3>

## Baseline Seed only model
<h3>determines winner based on who has higher seed</h3>
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Loading model dataset

df = pd.read_csv(MODEL_OUT)

#

data = df.copy()
data["T1_seed"] = pd.to_numeric(data["T1_seed"], errors="coerce")
data["T2_seed"] = pd.to_numeric(data["T2_seed"], errors="coerce")
data = data.dropna(subset=["T1_seed", "T2_seed", "Team1Win"])
data["T1_seed"] = data["T1_seed"].astype(int)
data["T2_seed"] = data["T2_seed"].astype(int)
data["seed_diff"] = data["T1_seed"] - data["T2_seed"]
data["lo_seed"] = data[["T1_seed", "T2_seed"]].min(axis=1)
data["hi_seed"] = data[["T1_seed", "T2_seed"]].max(axis=1)
data["lo_won"] = np.where(
    data["T1_seed"] < data["T2_seed"],
    data["Team1Win"],
    1 - data["Team1Win"]
)

#train test split

train, test = train_test_split(data, test_size=0.2, random_state=42, stratify=data["Team1Win"])

#1. Seed only logistic regression

seed_model = LogisticRegression(max_iter=1000)
seed_model.fit(train[["seed_diff"]], train["Team1Win"])
seed_preds = seed_model.predict(test[["seed_diff"]])
print(f"Seed Only Accuracy:   {accuracy_score(test['Team1Win'], seed_preds):.2%}")

# 2. Simple deterministic baseline: lower seed always wins

test_no_ties = test[test["seed_diff"] != 0].copy() #test data without tied seeds
det_preds = (test_no_ties["seed_diff"] < 0).astype(int)
print(f"Lower-seed-wins baseline:   {accuracy_score(test_no_ties['Team1Win'], det_preds):.2%}")




#3. Empirical matchup rates (built on train only)

rates = (
    train.groupby(["lo_seed", "hi_seed"])
    .agg(games=("lo_won", "count"), lo_wins=("lo_won", "sum"))
    .reset_index()
)
rates["win_rate"] = rates["lo_wins"] / rates["games"]

def predict_matchup(row):
    team1_seed = row["T1_seed"]
    team2_seed = row["T2_seed"]
    lower_seed = min(team1_seed, team2_seed)
    higher_seed = max(team1_seed, team2_seed)
 #Look up past games with this same seed matchup
    matchup = rates[
        (rates["lo_seed"] == lower_seed) &
        (rates["hi_seed"] == higher_seed)
    ]
    # If there is not enough data, predict that the better seed wins
    if matchup.empty or matchup["games"].values[0] < 20:
        team1_probability = 1 if team1_seed < team2_seed else 0
    else: #If there is enough data, use the historical win rate
        lower_seed_win_rate = matchup["win_rate"].values[0]

        if team1_seed < team2_seed:
            team1_probability = lower_seed_win_rate
        else:
            team1_probability = 1 - lower_seed_win_rate

    return int(team1_probability > 0.5)

test_no_ties = test[test["seed_diff"] != 0].copy()
test_no_ties["matchup_pred"] = test_no_ties.apply(predict_matchup, axis=1)
print(f"Empirical matchup baseline:   {accuracy_score(test_no_ties['Team1Win'], test_no_ties['matchup_pred']):.2%}")

#Rates table
print()
#print(rates.to_string(index=False))

"""## Logistic Regression Model
<h3>determines winner based on all difference features (no seeding, team 1 and team 2 are randomly swapped)</h3>
"""

##difference columns only

# All columns that compare winner - loser
diffCols = [col for col in df.columns if col.endswith("_diff")]

# Remove seeding columns
diffColsNoSeed = [
    col for col in diffCols
    if "seed" not in col.lower()
]


## randomly swap teams

rng = np.random.default_rng(42)

# Randomly decide whether Team1 is the actual winner
team1_is_winner = rng.integers(0, 2, size=len(df)) == 1

# If Team1 is winner, keep winner-loser diff
# If Team1 is loser, flip signs so features become Team1 - Team2
X = np.where(
    team1_is_winner.reshape(-1, 1),
    df[diffColsNoSeed].values,
    -df[diffColsNoSeed].values
)

X = pd.DataFrame(X, columns=diffColsNoSeed)

# Target variable
# 1 means Team1 won
# 0 means Team2 won
y = team1_is_winner.astype(int)

X = df[diffColsNoSeed].copy()
y = df["Team1Win"].copy()








##MODEL DEVELOPMENT TIME

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

#LOGISITC REGRESSION w/ Evaluation

model =  LogisticRegression(max_iter=5000, random_state=42).fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

accuracy = accuracy_score(y_test, y_pred)

print(f"Logistic Regression prediction accuracy: {accuracy:.2%}")
print()
print()

#logReg = model.named_steps["logisticregression"]

coefficients = pd.DataFrame({
    "Feature": diffColsNoSeed,
    "Coefficient": model.coef_[0]
})

coefficients["AbsValue"] = coefficients["Coefficient"].abs()

coefficients = coefficients.sort_values(
    by="AbsValue",
    ascending=False
)

print(coefficients.head(20))

"""## Random Forest Regression Model
<h3>determines winner based on all difference features (no seeding, team 1 and team 2 are randomly swapped)</h3>
"""

# RANDOM FOREST MODEL

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score
import pandas as pd

#train test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

rfModel = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    max_depth=5,    # 5 appeared to be the most optimal indicating simplye model
    min_samples_split=10,
    class_weight="balanced"
)

rfModel.fit(X_train, y_train)

y_pred_rf = rfModel.predict(X_test)
y_prob_rf = rfModel.predict_proba(X_test)[:, 1]

#accurate
rf_accuracy = accuracy_score(y_test, y_pred_rf)

print(f"Random Forest prediction accuracy: {rf_accuracy:.2%}")
print()

#training accuracy to check if overfit
train_pred_rf = rfModel.predict(X_train)
train_accuracy_rf = accuracy_score(y_train, train_pred_rf)

print(f"Random Forest train accuracy: {train_accuracy_rf:.2%}")
print(f"Random Forest test accuracy:  {rf_accuracy:.2%}")
print()

# Feature importances
rf_importances = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rfModel.feature_importances_
})

rf_importances = rf_importances.sort_values(
    by="Importance",
    ascending=False
)

print("Top 10 Random Forest Features")
print(rf_importances.head(10))

"""## Gradient Boosting
<h3>determines winner based on all difference features (no seeding, team 1 and team 2 are randomly swapped)</h3>
"""

# GRADIENT BOOSTING MODEL

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score
import pandas as pd


gbModel = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=2,
    min_samples_leaf=5,
    subsample=0.8,
    random_state=42
)

gbModel.fit(X_train, y_train)

# Predictions
y_pred_gb = gbModel.predict(X_test)

# Prediction probabilities
y_prob_gb = gbModel.predict_proba(X_test)[:, 1]

# Accuracy
gb_accuracy = accuracy_score(y_test, y_pred_gb)

print(f"Gradient Boosting prediction accuracy: {gb_accuracy:.2%}")
print()

# Train accuracy to check overfitting
train_pred_gb = gbModel.predict(X_train)
train_accuracy_gb = accuracy_score(y_train, train_pred_gb)

print(f"Gradient Boosting train accuracy: {train_accuracy_gb:.2%}")
print(f"Gradient Boosting test accuracy:  {gb_accuracy:.2%}")
print()

#AUC score
gb_auc = roc_auc_score(y_test, y_prob_gb)
print(f"Gradient Boosting AUC: {gb_auc:.3f}")
print()

#feature importance
gb_importances = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": gbModel.feature_importances_
})

gb_importances = gb_importances.sort_values(
    by="Importance",
    ascending=False
)

print("Top 10 Gradient Boosting Features")
print(gb_importances.head(10))




## Neural Network

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import numpy as np

# Neural Network

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

X_train_t = torch.tensor(X_train_scaled, dtype=torch.float32)
X_test_t  = torch.tensor(X_test_scaled,  dtype=torch.float32)
y_train_t = torch.tensor(y_train.values if hasattr(y_train, "values") else y_train, dtype=torch.float32)
y_test_t  = torch.tensor(y_test.values  if hasattr(y_test,  "values") else y_test,  dtype=torch.float32)

train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=32, shuffle=True)

class Net(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 64), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(64, 32),        nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(32, 1),         nn.Sigmoid()
        )
    def forward(self, x):
        return self.net(x).squeeze()

torch.manual_seed(42)
np.random.seed(42)

model_nn  = Net(X_train_scaled.shape[1])
optimizer = optim.Adam(model_nn.parameters(), lr=1e-3)
criterion = nn.BCELoss()
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=50, gamma=0.5)

epoch_accs = []

for epoch in range(40):
    model_nn.train()
    for xb, yb in train_loader:
        optimizer.zero_grad()
        loss = criterion(model_nn(xb), yb)
        loss.backward()
        optimizer.step()
    scheduler.step()

    model_nn.eval()
    with torch.no_grad():
        val_acc = ((model_nn(X_test_t) > 0.5).float() == y_test_t).float().mean().item()
    epoch_accs.append(val_acc)

    if (epoch + 1) % 5 == 0:
        print(f"Epoch {epoch+1:3d} — val accuracy: {val_acc:.2%}")

model_nn.eval()
with torch.no_grad():
    nn_probs = model_nn(X_test_t).numpy()
    nn_preds = (nn_probs > 0.5).astype(int)

nn_acc = accuracy_score(y_test, nn_preds)
print(f"\nNeural Network prediction accuracy: {nn_acc:.2%}")

print("Part 4 complete")

# PART 5: Visualizing and Interpreting Models


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.inspection import permutation_importance
from sklearn.metrics import accuracy_score
import torch
import seaborn as sns

model_results = []

# Baseline
model_results.append({"Model": "Empirical Matchup", "Accuracy": 0.7391})

# Logistic Regression
log_pred = model.predict(X_test)
model_results.append({"Model": "Logistic Regression", "Accuracy": accuracy_score(y_test, log_pred)})

# Random Forest
rf_pred = rfModel.predict(X_test)
model_results.append({"Model": "Random Forest", "Accuracy": accuracy_score(y_test, rf_pred)})

# Gradient Boosting
gb_pred = gbModel.predict(X_test)
model_results.append({"Model": "Gradient Boosting", "Accuracy": accuracy_score(y_test, gb_pred)})


# Neural Network
model_nn.eval()
with torch.no_grad():
    nn_probs = model_nn(torch.tensor(X_test_scaled, dtype=torch.float32)).numpy().ravel()
nn_pred = (nn_probs > 0.5).astype(int)
model_results.append({"Model": "Neural Network", "Accuracy": accuracy_score(y_test, nn_pred)})

performance_df = pd.DataFrame(model_results)

# Colors
model_colors = {
    "Baseline (Empirical) Matchup":   "darkgray",
    "Logistic Regression": "orange",
    "Random Forest":       "green",
    "Gradient Boosting":   "blue",
    "Neural Network":      "red",
}


# Plot 1: accuracy bar chart
accuracy_plot = performance_df.sort_values("Accuracy", ascending=False)
colors = [model_colors.get(m, "black") for m in accuracy_plot["Model"]]

plt.figure(figsize=(11, 6))
plt.bar(accuracy_plot["Model"], accuracy_plot["Accuracy"], color=colors, edgecolor="black")
plt.axhline(y=0.7609, color="gray", linestyle="--", linewidth=1.24)
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.ylim(0, 1)
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y", alpha=0.3)
plt.legend()
#labels accuracy charts
for index, accuracy in enumerate(accuracy_plot["Accuracy"]):
    x_position = index
    y_position = accuracy + 0.01

    label = f"{accuracy:.2%}"
    plt.text(
        x_position,
        y_position,
        label,
        ha="center"
    )
plt.tight_layout()
plt.show()





# Plot 2: permutation importance (ML models only)------
models = {
    "Logistic Regression": model,
    "Random Forest":       rfModel,
    "Gradient Boosting":   gbModel,
}

importance_tables = []
for model_name, fitted_model in models.items():
    result = permutation_importance(fitted_model, X_test, y_test, n_repeats=10, random_state=42, scoring="accuracy")
    importance_tables.append(pd.DataFrame({
        "Feature":    X_test.columns,
        "Model":      model_name,
        "Importance": result.importances_mean,
    }))

all_importances = pd.concat(importance_tables, ignore_index=True)
all_importances["Importance"] = all_importances["Importance"].clip(lower=0)

top_features = (
    all_importances.groupby("Feature")["Importance"]
    .mean().sort_values(ascending=False).head(8).index
)

importance_pivot = (
    all_importances[all_importances["Feature"].isin(top_features)]
    .pivot_table(index="Feature", columns="Model", values="Importance")
    .fillna(0)
)
importance_pivot["Average"] = importance_pivot.mean(axis=1)
importance_pivot = importance_pivot.sort_values("Average", ascending=True).drop(columns="Average")

plot_colors = [model_colors.get(m, "black") for m in importance_pivot.columns]
importance_pivot.plot(kind="barh", figsize=(11, 7), color=plot_colors, edgecolor="black")
plt.title("Most Important Predictors Across Models")
plt.xlabel("Permutation Importance")
plt.ylabel("Feature")
plt.grid(axis="x", alpha=0.3)
plt.legend(title="Model")
plt.tight_layout()
plt.show()

# Top 10 features table
top_feature_table = (
    all_importances.groupby("Feature")["Importance"]
    .mean().sort_values(ascending=False).head(10).reset_index()
)
display(top_feature_table)




#Plot 3: Confusion matrices for all models
fig, axes = plt.subplots(1, 4, figsize=(18, 4))

preds = {
    "Logistic Regression": log_pred,
    "Random Forest":       rf_pred,
    "Gradient Boosting":   gb_pred,
    "Neural Network":      nn_pred,
}

for ax, (name, pred) in zip(axes, preds.items()):
    cm = confusion_matrix(y_test, pred)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax,
                xticklabels=["T2 Wins", "T1 Wins"],
                yticklabels=["T2 Wins", "T1 Wins"])
    ax.set_title(name)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")

plt.suptitle("Confusion Matrices", fontsize=14, y=1.02)
plt.tight_layout()
plt.show()






# Plot 4: ROC curves
from sklearn.metrics import roc_curve, auc

fig, ax = plt.subplots(figsize=(8, 6))

roc_models = {
    "Logistic Regression": model.predict_proba(X_test)[:, 1],
    "Random Forest":       rfModel.predict_proba(X_test)[:, 1],
    "Gradient Boosting":   gbModel.predict_proba(X_test)[:, 1],
    "Neural Network":      nn_probs,
}

for name, probs in roc_models.items():
    fpr, tpr, _ = roc_curve(y_test, probs)
    roc_auc = auc(fpr, tpr)
    ax.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.3f})", color=model_colors[name])

ax.plot([0, 1], [0, 1], "k--", label="Random (AUC = 0.500)")
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_title("ROC Curves")
ax.legend()
ax.grid(alpha=0.3)
plt.tight_layout()
plt.show()







# Plot 5: Predicted win probability distributions
fig, axes = plt.subplots(1, 4, figsize=(18, 4))

for ax, (name, probs) in zip(axes, roc_models.items()):
    for outcome, label, color in [(1, "Team1 Won", "steelblue"), (0, "Team1 Lost", "tomato")]:
        mask = np.array(y_test) == outcome
        ax.hist(probs[mask], bins=20, alpha=0.6, label=label, color=color)
    ax.set_title(name)
    ax.set_xlabel("Predicted P(Team1 Win)")
    ax.set_ylabel("Count")
    ax.legend(fontsize=8)

plt.suptitle("Predicted Probability Distributions", fontsize=14, y=1.02)
plt.tight_layout()
plt.show()





# Plot 6: Logistic regression coefficients - easiest to interpret so we have plot of just logistic
coef_df = pd.DataFrame({
    "Feature":     X_test.columns,
    "Coefficient": model.coef_[0]
}).sort_values("Coefficient")

colors_coef = ["tomato" if c < 0 else "steelblue" for c in coef_df["Coefficient"]]

plt.figure(figsize=(10, 7))
plt.barh(coef_df["Feature"], coef_df["Coefficient"], color=colors_coef, edgecolor="black")
plt.axvline(x=0, color="black", linewidth=0.8)
plt.title("Logistic Regression Coefficients")
plt.xlabel("Coefficient Value")
plt.grid(axis="x", alpha=0.3)
plt.tight_layout()
plt.show()